site_name: Accreditation Standard
site_author: 'Chris Sharp'

theme: 
  name: material
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'

nav:
    - Front: index.md
    - Background: standard/background.md
    - Rationale: standard/rationale.md
    - High-level Proposal: standard/proposal.md
    - SFIA-based standard: standard/sfia-based.md
    - Appendices: 
        Generic Skills: appendices/generic.md
        Data Analytics: appendices/data-analytics.md
        Cybersecurity: appendices/cybersecurity.md
        Web Developer: appendices/web-dev.md
        SFIA Skills: 
          - Overview: appendices/skills/index.md
          - Leadership: appendices/skills/leadership.md
          - Experience: appendices/skills/work-experience.md
          - ARCH: appendices/skills/arch.md
          - DTAN: appendices/skills/dtan.md
          - HCEV: appendices/skills/hcev.md
          - INCA: appendices/skills/inca.md
          - PROF: appendices/skills/prof.md
          - PROG: appendices/skills/prog.md
          - RELM: appendices/skills/relm.md
          - REQM: appendices/skills/reqm.md
          - SCTY: appendices/skills/scty.md
          - SINT: appendices/skills/sint.md

plugins:
    - search
    - markdownextradata
    - pdf-export:
        verbose: false
        combined: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - footnotes
  - markdown_blockdiag:
      format: svg

extra:
  spec:
    version: 2.4

extra_css:
  - 'stylesheets/extra.css'
